services:
  php:
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
    volumes:
      - ./:/app
    networks:
      - laravel
    depends_on:
      - todoList-db
    entrypoint: [ "sh", "-c", "composer install && chown -R www-data:www-data storage && php artisan migrate && (while true; do php artisan app:verificar-tarefas-vencimento; sleep 5; done) & php-fpm" ]

  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:80"
    depends_on:
      - php
    networks:
      - laravel

  todoList-db:
    image: mysql:8.0
    volumes:
      - .docker/db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: todoList-db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8888:80"
    networks:
      - laravel

  redis-todolist:
    image: redis:alpine
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
    networks:
     - laravel

  npm:
    image: node:current-alpine
    container_name: npm
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - laravel
    entrypoint: [ "sh", "-c", "npm install && npm run build && tail -f /dev/null" ]

networks:
  laravel:
    driver: bridge
